# Site settings

url: "https://kartikarora.me"

baseurl: ""

# Google tag settings
google-tag: "G-5GZC83CFKC"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: true

syntax-highlight: true

# Sections shown in the index page

pages_list:
  - label: "About"
    type: about
    href: "about"
    destination: "inline"
  - label: "Timeline"
    type: work
    href: "work"
    destination: "inline"
  - label: "Talks"
    type: talks
    href: "talks"
    destination: "internal"
  - label: "Articles"
    type: articles
    href: "https://medium.com/@kartikarora"
    destination: "external"
  - label: "Codelabs"
    type: articles
    href: "https://codelabs.kartikarora.me"
    destination: "external"

web-app-mode: true

# Icons for Web App mode 

icon-36p: "/img/icon192.png"
icon-48p: "/img/icon192.png"
icon-72p: "/img/icon192.png"
icon-96p: "/img/icon192.png"
icon-144p: "/img/icon192.png"
icon-192p: "/img/icon192.png"

#############
# HTML Head #
#############

author: "Kartik Arora"
lang: "en"
title: "Kartik Arora"
favicon: "/img/favicon.ico"
description: ""
keywords: "kartik, arora, chipset, blog, portfolio"

################
# Intro layout #
################

black-favicon: ""
background-img: ""
me-img: "/img/kartik.jpg"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: true
shuffle: true    # Shuffle the lines.
loop: true
loop-count: false # Set false for infinite loop, or set any number for finite loop.
type-speed: 2        # Default 10
start-delay: 10    # Default 200
delete-delay: 3000    # Default 5000
lines: # You can add HTML Tags in the Text
  - text: "The best thing about a <b>boolean</b> is even if you are wrong, you are only off by a <b>bit</b>!"
  - text: "Itâ€™s not a <b>bug</b> â€“ itâ€™s an <i>undocumented feature</i>!"
  - text: "In order to understand <b>recursion</b>, one must first <b>understand recursion</b>"
  - text: "Failure is not an option. It comes bundled with <b>Windows</b>!"
  - text: "Whoever said <i>money can't buy you happiness</i> obviously never bought themselves a <b>drum kit</b>"

###############
# Life Events #
###############

events:
  - image: "/img/timeline/bilue.png"
    title: "Android Engineer @ Bilue"
    year: "2020 - present"
    description: "Joined <a href=\"https://bilue.com.au\" target=\"_blank\" rel=\"nofollow\">Bilue</a> as an Android Engineer. Working with multiple clients, helping them make a better android product! "
    projects:
  - image: "/img/timeline/usyd.png"
    year: "2018 - 2019"
    title: "ðŸŽ“ Master's Graduation!"
    description: "Completed my Master's in Interaction Design and Electronic Arts from University of Sydney."
    projects:
  - image: "/img/timeline/manipal.png"
    title: "ðŸŽ“ Bachelor's Graduation!"
    year: "2013 - 2017"
    description: "Completion of Bacherlor's of Technology and Computer Science (after 4 fun years) from Manipal Institute of Technology, India"
    projects:
    - image: "/img/timeline/flico.svg"
      title: "Flico"
      year: "2017"
      description: "A new dimension to movies and TV shows! Flico by Flicsys Inc. "
    - image: "/img/timeline/trsh.png"
      title: "Transfer.sh"
      year: "2017"
      description: "Easy file sharing from your Android device! <br><br>View it on <a href=\"https://github.com/kartikarora/Transfer.sh\" target=\"_blank\" rel=\"nofollow\"><i class=\"fa-brands fa-github\"></i></a>"
    - image: "/img/timeline/wd.png"
      year: "2016"
      title: "Wear Dialer"
      description: "Dial a number directly from your wrist!<br>View it on <a href=\"https://github.com/kartikarora/WearDialer\" target=\"_blank\" rel=\"nofollow\"><i class=\"fa-brands fa-github\"></i></a>"
    - image: "/img/timeline/revels16.png"
      title: "Revels'16"
      year: "2016"
      description: "Team Lead for the app for college cultural fest.<br>View it on <a href=\"https://github.com/kartikarora/Revels\" target=\"_blank\" rel=\"nofollow\"><i class=\"fa-brands fa-github\"></i></a>"
    - image: "/img/timeline/tt15.png"
      title: "TechTatva'15"
      year: "2015"
      description: "Team Lead for college techfest app.<br>View it on <a href=\"https://github.com/kartikarora/TechTatva\" target=\"_blank\" rel=\"nofollow\"><i class=\"fa-brands fa-github\"></i></a>"
    - image: "/img/timeline/potato.png"
      title: "Potato Library"
      year: "2015"
      description: "Easy to use Utility library for Android.<br>Get it on <a href=\"http://kartikarora.me/Potato-Library\" target=\"_blank\" rel=\"nofollow\"><i class=\"fa-brands fa-github\"></i></a>"
    - image: "/img/timeline/uc.png"
      title: "Ultimate Challenge"
      year: "2010 - 2012"
    description: "Ran a gaming clan with a few friends. We regularly played Call of Duty, Need for Speed, Left 4 Dead 2. Quite enjoyed hosting the servers on <a href=\"https://www.gameranger.com\" rel=\"nofollow\">Game Ranger</a>"
  - image: "/img/timeline/espice.jpeg"
    title: "eSpice"
    year: "2009 - 2012"
    description: "Member of the computer science society of my high school. Hosted multiple events, interschool symposiums, programming competitions!"
    projects:
  - image: "/img/timeline/cpp.png"
    title: "Started Programming"
    year: "2009"
    description: ""

# First image of the Career timeline

##################
# Contact layout #
##################

email: "aawaazdo@kartikarora.me"

##################
# Social Buttons #
##################

social:
  - title: "github"
    type: "brands"
    url: "https://github.com/kartikarora"
    on_nav: false
  - title: "linkedin"
    type: "brands"
    url: "https://linkedin.com/in/arorakartik"
    on_nav: true
  - title: "medium"
    type: "brands"
    url: "https://medium.com/@kartikarora"
    on_nav: true
  - title: "x-twitter"
    type: "brands"
    url: "https://twitter.com/kartikarora95"
    on_nav: false
  - title: "mastodon"
    type: "brands"
    url: "https://androiddev.social/@Kartikarora"
    on_nav: false
  - title: "keybase"
    type: "brands"
    url: "https://keybase.io/kartikarora"
    on_nav: false
  - title: "envelope"
    type: "solid"
    url: "mailto:aawaazdo@kartikarora.me"
    on_nav: true

############
# 404 page #
############

not-found-img: "/img/404.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: [ "LICENSE", "README", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "Gemfile", "Gemfile.lock", "CNAME" ]
include: [ "keybase.txt" ]

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jeykyll-gist
  - jemoji
  - jekyll-redirect-from


collections:
  urls:
    output: true
    permalink: /s/:slug

whitelist:
  - jekyll-redirect-from