
# Site settings

url: "http://kartikarora.me"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: "UA-69555022-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

syntax-highlight: True

# Sections shown in the index page

pages_list:
  About: 'about'
  Work: 'work'
  Contact: 'contact'
  Blog: 'latest-post'

web-app-mode: True

# Icons for Web App mode 

icon-36p: "/img/icon.ico"
icon-48p: "/img/icon.ico"
icon-72p: "/img/icon.ico"
icon-96p: "/img/icon.ico"
icon-144p: "/img/icon.ico"
icon-192p: "/img/icon.ico"

#############
# HTML Head #
#############

author: "Kartik Arora"
lang: "en"
title: "{ CHIPSET }"
favicon: "/img/icon.ico"
description: "Website, Portfolio and Blog of Kartik Arora"
keywords: "kartik, arora, chipset, blog, portfolio"

################
# Intro layout #
################

black-favicon: ""
background-img: ""
me-img: "https://avatars3.githubusercontent.com/u/6591617"

##############################
# Dynamic Text on the header #
##############################

dynamic-typing: True
shuffle: True	# Shuffle the lines.
loop: True
loop-count:	False # Set False for infinite loop, or set any number for finite loop.
type-speed:	10		# Default 10
start-delay: 200	# Default 200
delete-delay: 5000	# Default 5000
lines:			# You can add HTML Tags in the Text
  - text: "The best thing about a <b>boolean</b> is even if you are wrong, you are only off by a <b>bit</b>!"
  - text: "It’s not a <b>bug</b> – it’s an <b>undocumented feature</b>!"
  - text: "In order to understand <b>recursion</b>, one must first <b>understand recursion</b>"
  - text: "Failure is not an option. It comes bundled with <b>Windows</b>!"
  - text: "<b><i>Linux<i></b> is Truth"
  - text: "Whoever said <i>money can't buy you happiness</i> obviously never bought themselves a <b>drum kit</b>"

########
# Blog #
########

post-preview-words: 99

paginate: 5

email-share: True
fb-share: True
twitter-share: True
reddit-share: True
google-plus-share: True
linkedin-share: True
tumblr-share: True
pinterest-share: False
vkontakte-share: False
disqus-shortname: "chipset95"

###############
# Life Events #
###############

events:
  - image: "/img/timeline/flico.svg"
    title: "Flico"
    description: "A new dimension to movies and TV shows! Flico by Flicsys Inc. Checkout the website <a href=\"http://flico.me\" target=\"_blank\"><i class=\"fa fa-globe\"></i><a>"
  - image: "/img/timeline/trsh.png"
    title: "Transfer.sh"
    description: "Easy file sharing from your Android device! <br>Download App from <a href=\"https://play.google.com/store/apps/details?id=me.kartikarora.transfersh\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/kartikarora/Transfer.sh\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/timeline/wd.png"
    title: "Wear Dialer"
    description: "Dial a number directly from your wrist!<br>Download App from <a href=\"https://play.google.com/store/apps/details?id=chipset.weardialer\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/kartikarora/WearDialer\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/timeline/tt15.png"
    title: "TechTatva'15"
    description: "Team Lead for college techfest app.<br>Download App from <a href=\"https://play.google.com/store/apps/details?id=chipset.techtatva\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/kartikarora/TechTatva\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/timeline/revels16.png"
    title: "Revels'16"
    description: "Team Lead for college for college cultural fest.<br>Download App from <a href=\"https://play.google.com/store/apps/details?id=chipset.revels\" target=\"_blank\">Play Store</a><br>View it on <a href=\"https://github.com/kartikarora/Revels\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/timeline/potato.png"
    title: "Potato Library"
    description: "Easy to use Utility library for Android.<br>Get it on <a href=\"http://kartikarora.me/Potato-Library\" target=\"_blank\"><i class=\"fa fa-github\"></i></a>"
  - image: "/img/timeline/cpp.png"
    title: "Started Coding"
    description: "TurboC++ 3, the first IDE I used. Marked the begining of my journey in the amazing world of programming"

# First image of the Career timeline
career-img: "/img/timeline/rma2.png"

##################
# Contact layout #
##################

email: "aawaazdo@kartikarora.me"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/kartikarora"
  - title: "twitter"
    url: "https://twitter.com/kartikarora95"
  - title: "youtube"
    url: "https://youtube.com/kartikarora"
  - title: "linkedin"
    url: "https://in.linkedin.com/in/arorakartik"
  - title: "angellist"
    url: "https://angel.co/kartikarora"
  - title: "envelope"
    url: "mailto:aawaazdo@kartikarora.me"
  - title: "rss"
    url: "/feed.xml"

##################
# GPG on Keybase #
##################

keybase-username: kartikarora
keybase-in-social: True
keybase-in-footer: True

############
# 404 page #
############

404-img: "/img/404.png"

################################################################################

# Tread carefully if you want to change the variables below this point!

# Exclusion list from the generated _site

exclude: ["LICENSE", "README", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]
include: ["keybase.txt"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
